apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    database: ecologie_data
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      sslmode: "disable"
